CREATE DATABASE IF NOT EXISTS juridico;

USE juridico;

CREATE TABLE IF NOT EXISTS conversas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sessao_id VARCHAR(50) NOT NULL,
  role VARCHAR(50) NOT NULL,
  message TEXT NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);